
#-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->
# Path of libft.h WITHOUT .h file!  e.g
# LIBFT_PATH = /Users/LIBFT/+libft 	[/libft.h]

LIBFT_PATH_TEST	= /Users/mariemensing/LIBFT/+libft

# :)
#-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->


LIBFT_PATH_MY		= /Users/mariemensing/LIBFT/+libft
NAME				= my_libft_tester.a
CC				= gcc
RM				= rm -rf
HEAD				= head.h
FLAGS			= -c -Wall -Werror -Wextra
EXEC_LIB_MY		= -L$(LIBFT_PATH_MY) -lft
EXEC_LIB_TEST		= -L$(LIBFT_PATH_TEST) -lft


# for 'test.c' my lib!
test:
	@gcc test.c $(EXEC_LIB_MY)
	@./a.out

01:
	@echo "\n"ft_isalpha.c:
	@gcc 01_isalpha.c $(EXEC_LIB_TEST)
	@./a.out
02:
	@echo "\n"ft_isdigit.c:
	@gcc 02_isdigit.c $(EXEC_LIB_TEST)
	@./a.out
03:
	@echo "\n"ft_isalnum.c:
	@gcc 03_isalnum.c $(EXEC_LIB_TEST)
	@./a.out

04:
	@echo "\n"ft_isascii.c:
	@gcc 04_isascii.c $(EXEC_LIB_TEST)
	@./a.out

05:
	@echo "\n"ft_isprint.c:
	@gcc 05_isprint.c $(EXEC_LIB_TEST)
	@./a.out

06:
	@echo "\n"ft_strlen.c:
	@gcc 06_strlen.c $(EXEC_LIB_TEST)
	@./a.out

07:
	@echo "\n"ft_memset.c:
	@gcc 07_memset.c $(EXEC_LIB_TEST)
	@./a.out

08:
	@echo "\n"ft_bzero.c:
	@gcc 08_bzero.c $(EXEC_LIB_TEST)
	@./a.out

09:
	@echo "\n"ft_memcpy.c:
	@gcc 09_memcpy.c $(EXEC_LIB_TEST)
	@./a.out

10:
	@echo "\n"ft_memmove.c:
	@gcc 10_memmove.c $(EXEC_LIB_TEST)
	@./a.out

11:
	@echo "\n"ft_strlcpy.c:
	@gcc 11_strlcpy.c $(EXEC_LIB_TEST)
	@./a.out

12:
	@echo "\n"ft_strlcat.c:
	@gcc 12_strlcat.c $(EXEC_LIB_TEST)
	@./a.out

13:
	@echo "\n"ft_toupper.c:
	@gcc 13_toupper.c $(EXEC_LIB_TEST)
	@./a.out

14:
	@echo "\n"ft_tolower.c:
	@gcc 14_tolower.c $(EXEC_LIB_TEST)
	@./a.out

15:
	@echo "\n"ft_strchr.c:
	@gcc 15_strchr.c $(EXEC_LIB_TEST)
	@./a.out
16:
	@echo "\n"ft_strrchr.c:
	@gcc 16_strrchr.c $(EXEC_LIB_TEST)
	@./a.out
17:
	@echo "\n"ft_strncmp.c:
	@gcc 17_strncmp.c $(EXEC_LIB_TEST)
	@./a.out
18:
	@echo "\n"ft_memchr.c:
	@gcc 18_memchr.c $(EXEC_LIB_TEST)
	@./a.out
19:
	@echo "\n"ft_memcmp.c:
	@gcc 19_memcmp.c $(EXEC_LIB_TEST)
	@./a.out
del:
	@echo "\n""\t"... deleletely output files ..."\n"
	@$(RM) *.out
	@$(RM) *.o

clean: del
	@echo "\n""->> -██████ ██╗---- ███████╗ █████╗ ███╗---██╗""\n""->> ██╔════ ██║---- ██╔════ ██╔══██ ████╗--██║""\n""->> ██║---- ██║---- █████╗- ███████ ██╔██╗-██║""\n""->> ██║---- ██║---- ██╔══╝- ██╔══██ ██║╚██╗██║""\n""->> ╚██████ ███████ ███████ ██║--██ ██║-╚████║""\n""->> -╚═════ ╚══════ ╚══════ ╚═╝--╚═ ╚═╝--╚═══╝""\n"""

.PHONY: clean tests 01 02 03 04 05 06 07 08 09 10 11 12 del


